### ISSUE TITLE
helm install fails

### ISSUE THREAD

**Issue by hafeezpk** [mbenabda/helm-local-chart-version#15]
[0mPreparing to install into 
[91mmkdir: missing operand
Try 'mkdir --help' for more information.
[0mFailed to install helm-local-chart-version
For support, go to https://github.com/mbenabda/helm-local-chart-version.
The command '/bin/sh -c helm plugin install https://github.com/mbenabda/helm-local-chart-version         && sh $(helm home)/plugins/helm-local-chart-version/install-binary.sh         && helm plugin install https://github.com/chartmuseum/helm-push         && chmod 777 -R /usr/local/helm' returned a non-zero code: 1

**Comment by hafeezpk** [comment]
#Install helm
RUN wget https://git.io/get_helm.sh && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh && \
    rm get_helm.sh

RUN export HELM_HOME=/usr/local/helm && \
    helm init --client-only

ENV HELM_HOME=/usr/local/helm

RUN helm plugin install https://github.com/mbenabda/helm-local-chart-version \
        && sh $(helm home)/plugins/helm-local-chart-version/install-binary.sh \
        && helm plugin install https://github.com/chartmuseum/helm-push \
        && chmod 777 -R /usr/local/helm

**Comment by hafeezpk** [comment]
Probably && sh $(helm home)/plugins/helm-local-chart-version/install-binary.sh is the problem

**Comment by mbenabda** [comment]
hi there.
I suppose you're trying to install over the latest helm version ?
Tha looks similar to #11 which has been fixed in v0.0.7 with [commit 9b6d2d72](https://github.com/mbenabda/helm-local-chart-version/commit/28c914428bdeb479a67d37b29e2fd61d) 

please try explicitely installing version v0.0.7 of the plugin 
```sh
helm plugin install https://github.com/mbenabda/helm-local-chart-version --version 0.0.7
```

If that doesn't help, please provide the helm version, the base distribution you're building you docker image upon, so i can reproduce

let me know how it goes.

**Comment by mbenabda** [comment]
hi there. did it help ?

**Comment by mbenabda** [comment]
hi there @hafeezpk did it help ?

**Comment by hafeezpk** [comment]
I just removed && sh $(helm home)/plugins/helm-local-chart-version/install-binary.sh
and proceeded :)

**Comment by mbenabda** [comment]
oh i just noticed the double install ...
glad you got it working.
